services:
  - type: web
    name: agrisense-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: TYPEORM_SYNCHRONIZE
        value: "false"
      - key: SEED_ADMIN_EMAIL
        value: nibishaka.dev@gmail.com
      - key: SEED_ADMIN_FIRST_NAME
        value: Nibishaka
      - key: SEED_ADMIN_LAST_NAME
        value: Admin
      - key: SEED_ADMIN_PASSWORD
        sync: false

      # PostgreSQL (external, e.g. Neon)
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"

      # Redis (Upstash – external)
      - key: REDIS_URL
        sync: false

      - key: JWT_SECRET
        generateValue: true
